const $=(s,root=document)=>root.querySelector(s),$$=(s,root=document)=>[...root.querySelectorAll(s)];
let editIndex=null,treeMode=false,selectedMonth='',activeConfigIndex=null,previewMode='calendar',monthPanelCollapsed=false,calendarCollapsed=false,viewConfigIndex=null,flatPage=1,flatPageSize=20,rangeDraftStart='',rangeDraftEnd='',rangeCalendarMonth='',activeProblemBatch='',problemEditingId='',pendingImportPlan=null,importSequence=4;
const selectedPolicies=new Set();
const selectedProblemIds=new Set();
const defaults={dailyBase:500,workdayBase:650,sundayBase:600,holidayBase:700,dailyPrice:'0.01',workdayPrice:'0.01',sundayPrice:'0.02',holidayPrice:'0.02'};
const holidayNames=new Map(),holidayLoadedYears=new Set();
function addHolidayRange(start,end,name){const d=new Date(`${start}T00:00:00`),last=new Date(`${end}T00:00:00`);while(d<=last){holidayNames.set(formatDate(d),name);d.setDate(d.getDate()+1)}}
function loadOfficialHolidays2026(){[['2026-01-01','2026-01-03','元旦'],['2026-02-15','2026-02-23','春节'],['2026-04-04','2026-04-06','清明节'],['2026-05-01','2026-05-05','劳动节'],['2026-06-19','2026-06-21','端午节'],['2026-09-25','2026-09-27','中秋节'],['2026-10-01','2026-10-07','国庆节']].forEach(x=>addHolidayRange(...x));holidayLoadedYears.add(2026)}
const flowSamples=[
  ['771990','虚拟广西省区'],['371990','虚拟河南省区'],['279990','虚拟湖北省区'],['731990','虚拟湖南省区'],
  ['259990','江苏经营本部'],['791990','虚拟江西省区'],['109990','京津冀经营本部'],['531990','山东经营本部'],
  ['219990','虚拟上海省区'],['288990','虚拟四川省区'],['299990','虚拟西北省区'],['571990','浙江经营本部'],
  ['551990','虚拟安徽省区'],['411991','虚拟东北省区'],['591990','虚拟福建省区'],['209990','广东经营本部']
];
const siteSamples=[
  {code:'8590006',name:'安龙站',month:'2026-06',start:'2026-06-01',end:'2026-06-30',base:350,workday:500,sunday:350},
  {code:'8510052',name:'安顺商贸城S站',month:'2026-06',start:'2026-06-01',end:'2026-06-30',base:500,workday:500,sunday:500},
  {code:'8510088',name:'贵阳花溪S站',month:'2026-07',start:'2026-07-01',end:'2026-07-31',base:450,workday:600,sunday:450}
];
const productOptions=['融速达','精准零担'],cargoOptions=['轻泡','重泡','重货'],bandOptions=['0kg-100kg','100kg-300kg','300kg-800kg','800kg-1500kg'];
function expandCombinations(base){const products=splitMulti(base.product),cargos=splitMulti(base.cargo),bands=splitMulti(base.band);return products.flatMap(product=>cargos.flatMap(cargo=>bands.map(band=>({...base,product,cargo,band}))))}
const configs=siteSamples.flatMap((site,siteIndex)=>flowSamples.flatMap(([endpointCode,endpoint],flowIndex)=>{
  const isSichuan=site.name==='安龙站'&&endpoint==='虚拟四川省区';
  const isProvidedSample=(site.name==='安龙站'&&flowIndex<12)||(site.name==='安顺商贸城S站'&&flowIndex>=12);
  const baseAdjust=siteIndex===1?[50,0,-150,0][flowIndex%4]:0;
  const workdayAdjust=siteIndex===1&&flowIndex%4===3?140:0;
  return expandCombinations({
    ...defaults,
    month:site.month,siteCode:site.code,site:site.name,endType:'营运区',endpointCode,endpoint,
    product:productOptions.join(','),cargo:(isSichuan?['轻泡']:cargoOptions).join(','),band:bandOptions.join(','),
    start:site.start,end:site.end,holidayDate:'2026-06-19',cycle:isProvidedSample?'月':(flowIndex%2?'周':'月'),
    dailyBase:site.base+baseAdjust,workdayBase:site.workday+workdayAdjust,sundayBase:site.sunday,
    holidayBase:site.sunday,dailyPrice:'0.03',workdayPrice:'0.03',sundayPrice:'0.03',holidayPrice:'0.03',
    enabled:!(siteIndex===2&&flowIndex%7===0),importedAt:`2026-09-${String(10+siteIndex).padStart(2,'0')} ${String(9+flowIndex%8).padStart(2,'0')}:18`,importedBy:siteIndex===1?'王敏':'李未'
  })
}));
const systemNow=new Date(),currentMonth=`${systemNow.getFullYear()}-${String(systemNow.getMonth()+1).padStart(2,'0')}`;
const availableMonths=new Set(configs.map(r=>r.month));
availableMonths.add(currentMonth);
const importRows=[['IMP20260918001','网点返利政策_2026年10月.xlsx','处理中',286540,198320,0,0,'李未','2026-09-18 09:18'],['IMP20260917002','网点返利政策_2026年9月.xlsx','导入成功',238126,238126,0,0,'李未','2026-09-17 10:18'],['IMP20260916003','网点返利政策_补充.xlsx','部分失败',82420,82039,381,12,'李未','2026-09-16 17:42']];
const problemReasons=['生效开始日期缺失','货物类型枚举无法识别','公斤段格式错误','与已启用政策重复'];
const problemRows=Array.from({length:381},(_,index)=>{const type=index%4,site=siteSamples[index%siteSamples.length],flow=flowSamples[index%flowSamples.length];return {id:`ERR${String(index+1).padStart(5,'0')}`,batch:'IMP20260916003',rowNo:index+2,start:type===0?'':site.start,end:site.end,site:site.name,endpoint:flow[1],product:productOptions[index%productOptions.length],cargo:type===1?'超重货':cargoOptions[index%cargoOptions.length],band:type===2?'100-300':bandOptions[index%bandOptions.length],cycle:index%2?'周':'月',dailyBase:site.base,dailyPrice:'0.0300',workdayBase:site.workday,workdayPrice:'0.0300',sundayBase:site.sunday,sundayPrice:'0.0300',holidayBase:site.sunday,holidayPrice:'0.0300',reason:problemReasons[type],status:'待修改'}});
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),3000)}
function formatDate(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function monthOf(date){return date.slice(0,7)}
function daysInMonth(value){const [y,m]=value.split('-').map(Number);return new Date(y,m,0).getDate()}
function latestMonth(){return [...configs].sort((a,b)=>b.month.localeCompare(a.month))[0]?.month||'2026-09'}
function sortedConfigs(rows){return [...rows].sort((a,b)=>b.end.localeCompare(a.end)||b.start.localeCompare(a.start))}
function getDateMeta(date){const d=new Date(`${date}T00:00:00`),dayGroup=d.getDay()===0?'周日':'工作日';return {type:holidayNames.has(date)?'法定节假日':dayGroup,dayGroup,d}}
function usable(v){return v!==''&&v!==null&&v!==undefined&&!Number.isNaN(Number(v))}
function effectiveValue(r,date,kind){const {type,dayGroup}=getDateMeta(date),daily=r[kind==='base'?'dailyBase':'dailyPrice'],workday=r[kind==='base'?'workdayBase':'workdayPrice'],sunday=r[kind==='base'?'sundayBase':'sundayPrice'],holiday=r[kind==='base'?'holidayBase':'holidayPrice'];if(type==='法定节假日'&&usable(holiday))return holiday;const category=dayGroup==='周日'?sunday:workday;return usable(category)?category:daily}
function tableRow(r,index,scope){const date=`<span class="date-inline">${r.start}<span class="muted"> 至 </span>${r.end}</span>`,first=`<td>${date}</td>`,enabled=r.enabled!==false,viewing=index===viewConfigIndex;return `<tr class="policy-row ${scope==='month'&&index===activeConfigIndex?'active':''} ${viewing?'viewing':''}" data-row-index="${index}" aria-selected="${viewing}"><td><input class="checkbox row-selector" type="checkbox" data-select-row="${index}" aria-label="选择${r.site}至${r.endpoint}配置" ${selectedPolicies.has(r)?'checked':''} /></td>${first}<td>${r.site}</td><td>${r.endpoint}</td><td>${r.product}</td><td>${r.cargo}</td><td>${r.band}</td><td>${r.cycle}</td><td><span class="tag ${enabled?'orange':''}">${enabled?'启用':'停用'}</span></td><td><span class="date-inline">${r.importedAt||'—'}</span></td><td>${r.importedBy||'—'}</td><td><button class="btn text" data-row-action="view" data-index="${index}">查看</button><button class="btn text" data-row-action="edit" data-index="${index}">编辑</button><button class="btn text" data-row-action="delete" data-index="${index}" style="color:var(--danger)">删除</button></td></tr>`}
function inlineCalendarRow(r,index,scope){const colspan=12;return `<tr class="inline-calendar-row"><td colspan="${colspan}"><section class="inline-calendar-panel" aria-label="每日配置日历"><div class="inline-calendar-head"><div class="inline-calendar-actions"><button class="btn text" type="button" data-inline-calendar-action="close">关闭</button></div></div><div class="inline-calendar-content">${calendarHtml(r)}</div></section></td></tr>`}
const policyFilterMeta={site:'请选择网点',endpoint:'请选择流向',cargo:'请选择类型',band:'请选择公斤段',cycle:'请选择周期'};
const fixedFilterValues={cycle:['周','月']};
function splitMulti(value){return String(value||'').split(',').map(x=>x.trim()).filter(Boolean)}
const editorMultiMeta={
  product:{placeholder:'请选择产品类型',values:['融汇达','精准零担','融安达','融速达']},
  cargo:{placeholder:'请选择货物类型',values:cargoOptions},
  band:{placeholder:'请选择公斤段',values:bandOptions}
};
function editorMultiValues(key){return $$(`input[value]`,$(`[data-editor-multi="${key}"]`)).filter(item=>item.checked).map(item=>item.value)}
function updateEditorMultiSummary(key){const detail=$(`[data-editor-multi="${key}"]`),meta=editorMultiMeta[key],selected=editorMultiValues(key),summary=$('summary',detail);summary.innerHTML=selected.length?`<span class="multi-tag-list">${selected.map(value=>`<span class="filter-tag"><span>${value}</span><button type="button" data-remove-editor-value="${value}" aria-label="删除${value}">×</button></span>`).join('')}</span>`:`<span class="multi-placeholder">${meta.placeholder}</span>`}
function setEditorMultiValues(key,values=[]){const selected=new Set(values);const detail=$(`[data-editor-multi="${key}"]`);$$('input[value]',detail).forEach(item=>{item.checked=selected.has(item.value)});const all=$('[data-select-all-editor]',detail);if(all)all.checked=selected.size===editorMultiMeta[key].values.length;updateEditorMultiSummary(key)}
function updateCombinationHint(){const productCount=editorMultiValues('product').length,cargoCount=editorMultiValues('cargo').length,bandCount=editorMultiValues('band').length,start=$('#eStart').value,end=$('#eEnd').value,monthCount=start&&end&&start<=end?splitByMonth({start,end}).length:0,typeCount=productCount*cargoCount*bandCount,total=typeCount*monthCount;$('#combinationHint').textContent=!typeCount?'请选择产品类型、货物类型和公斤段；三个字段均为必选。':(!monthCount?`已选择 ${productCount} × ${cargoCount} × ${bandCount}，共 ${typeCount} 个类型组合；请填写有效生效日期。`:`已选择 ${productCount} 个产品类型 × ${cargoCount} 个货物类型 × ${bandCount} 个公斤段，共 ${typeCount} 个类型组合；生效范围拆分为 ${monthCount} 个自然月，提交后生成 ${total} 条原子政策。`)}
function renderEditorMultiSelects(){Object.entries(editorMultiMeta).forEach(([key,meta])=>{const detail=$(`[data-editor-multi="${key}"]`),box=$('.multi-options',detail);box.innerHTML=`<label class="multi-option multi-option-all"><input type="checkbox" data-select-all-editor="${key}" />全选</label>${meta.values.map(value=>`<label class="multi-option"><input type="checkbox" value="${value}" />${value}</label>`).join('')}`;box.addEventListener('change',event=>{const items=$$('input[value]',box),all=$('[data-select-all-editor]',box);if(event.target===all)items.forEach(item=>item.checked=all.checked);else all.checked=items.length>0&&items.every(item=>item.checked);updateEditorMultiSummary(key);updateCombinationHint()});$('summary',detail).addEventListener('click',event=>{const remove=event.target.closest('[data-remove-editor-value]');if(!remove)return;event.preventDefault();event.stopPropagation();const input=$$('input[value]',box).find(item=>item.value===remove.dataset.removeEditorValue);if(input)input.checked=false;const all=$('[data-select-all-editor]',box);if(all)all.checked=false;updateEditorMultiSummary(key);updateCombinationHint()});updateEditorMultiSummary(key)})}
function updateFilterDateText(){const start=$('#filterStart').value,end=$('#filterEnd').value;$('#filterDateText').textContent=start&&end?`${start} 至 ${end}`:(start?`${start} 起`:(end?`截至 ${end}`:'请选择时间段'))}
function closeFilterDatePicker(){const popover=$('#filterDatePopover'),trigger=$('#filterDateRange');popover.classList.add('hidden');trigger.setAttribute('aria-expanded','false')}
function renderRangeCalendar(){const [year,month]=rangeCalendarMonth.split('-').map(Number),count=new Date(year,month,0).getDate(),firstDay=new Date(year,month-1,1).getDay();$('#rangeMonthLabel').textContent=`${year}年${month}月`;$('#rangeCalendarDays').innerHTML=`${'<span class="range-day-empty"></span>'.repeat(firstDay)}${Array.from({length:count},(_,index)=>{const date=`${rangeCalendarMonth}-${String(index+1).padStart(2,'0')}`,isStart=date===rangeDraftStart,isEnd=date===rangeDraftEnd,inRange=rangeDraftStart&&rangeDraftEnd&&date>rangeDraftStart&&date<rangeDraftEnd;return `<button class="range-day ${isStart?'range-start':''} ${isEnd?'range-end':''} ${inRange?'in-range':''}" type="button" data-range-date="${date}"><span>${index+1}</span></button>`}).join('')}`;$('#rangeSelectionTip').textContent=!rangeDraftStart?'请选择开始日期':(!rangeDraftEnd?`开始日期：${rangeDraftStart}，请选择结束日期`:`已选择：${rangeDraftStart} 至 ${rangeDraftEnd}`);$('#filterDateConfirm').disabled=!(rangeDraftStart&&rangeDraftEnd)}
function moveRangeMonth(offset){const [year,month]=rangeCalendarMonth.split('-').map(Number),date=new Date(year,month-1+offset,1);rangeCalendarMonth=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`;renderRangeCalendar()}
function renderPolicyFilters(){Object.entries(policyFilterMeta).forEach(([key,placeholder])=>{const detail=$(`.multi-select[data-filter="${key}"]`),box=$('.multi-options',detail),values=[...new Set([...(fixedFilterValues[key]||[]),...configs.flatMap(row=>splitMulti(row[key]))])].sort((a,b)=>a.localeCompare(b,'zh-CN')),searchable=detail.dataset.searchable==='true';box.innerHTML=`${searchable?`<div class="multi-search-wrap"><input class="multi-search" type="search" placeholder="输入名称搜索" aria-label="搜索${placeholder.replace('请选择','')}" /></div>`:''}<label class="multi-option multi-option-all"><input type="checkbox" data-select-all-filter="${key}" />全选</label>${values.map(value=>`<label class="multi-option"><input type="checkbox" value="${value}" />${value}</label>`).join('')}${searchable?'<div class="multi-no-result hidden">没有匹配项</div>':''}`;box.addEventListener('change',event=>{const all=$(`[data-select-all-filter="${key}"]`,box),items=$$('input[value]',box);if(event.target===all)items.forEach(item=>item.checked=all.checked);else all.checked=items.length>0&&items.every(item=>item.checked);updateFilterSummary(detail,key,placeholder)});$('summary',detail).addEventListener('click',event=>{const remove=event.target.closest('[data-remove-filter]');if(!remove)return;event.preventDefault();event.stopPropagation();const input=$$('input[value]',box).find(item=>item.value===remove.dataset.removeFilter);if(input)input.checked=false;const all=$(`[data-select-all-filter="${key}"]`,box);if(all)all.checked=false;updateFilterSummary(detail,key,placeholder)});if(searchable){const search=$('.multi-search',box),noResult=$('.multi-no-result',box);search.addEventListener('input',()=>{const keyword=search.value.trim().toLocaleLowerCase('zh-CN');let visible=0;$$('.multi-option:not(.multi-option-all)',box).forEach(label=>{const show=!keyword||$('input',label).value.toLocaleLowerCase('zh-CN').includes(keyword);label.classList.toggle('hidden',!show);if(show)visible+=1});noResult.classList.toggle('hidden',visible>0)})}updateFilterSummary(detail,key,placeholder)})}
function updateFilterSummary(detail,key,placeholder){const selected=$$('input[value]',detail).filter(item=>item.checked),summary=$('summary',detail);summary.innerHTML=selected.length===0?`<span class="multi-placeholder">${placeholder}</span>`:`<span class="multi-tag-list">${selected.map(item=>`<span class="filter-tag"><span>${item.value}</span><button type="button" data-remove-filter="${item.value}" aria-label="删除${item.value}">×</button></span>`).join('')}</span>`}
function selectedFilterValues(key){const detail=$(`.multi-select[data-filter="${key}"]`),items=$$('input[value]',detail),selected=items.filter(item=>item.checked).map(item=>item.value);return selected.length===0||selected.length===items.length?null:selected}
function filteredPolicies(){const start=$('#filterStart')?.value||'',end=$('#filterEnd')?.value||'',enabled=$('#filterEnabled')?.value||'',selected=Object.fromEntries(Object.keys(policyFilterMeta).map(key=>[key,selectedFilterValues(key)]));return configs.filter(row=>{if(start&&row.end<start)return false;if(end&&row.start>end)return false;if(enabled==='enabled'&&row.enabled===false)return false;if(enabled==='disabled'&&row.enabled!==false)return false;return Object.entries(selected).every(([key,values])=>!values||splitMulti(row[key]).some(value=>values.includes(value)))})}
function compactPages(total,current){if(total<=7)return Array.from({length:total},(_,i)=>i+1);const pages=[1],start=Math.max(2,current-1),end=Math.min(total-1,current+1);if(start>2)pages.push('left-gap');for(let page=start;page<=end;page+=1)pages.push(page);if(end<total-1)pages.push('right-gap');pages.push(total);return pages}
function selectionScopeRows(scope){return scope==='flat'?filteredPolicies():configs.filter(r=>r.month===selectedMonth)}
function updateBulkSelectionUi(){const count=selectedPolicies.size,disableButton=$('#bulkDisableBtn'),deleteButton=$('#bulkDeleteBtn');disableButton.disabled=count===0;deleteButton.disabled=count===0;disableButton.textContent=count?`批量停用（已选 ${count} 条）`:'批量停用';deleteButton.textContent=count?`批量删除（已选 ${count} 条）`:'批量删除';$$('[data-select-all]').forEach(all=>{const rows=selectionScopeRows(all.dataset.selectAll),selectedCount=rows.filter(row=>selectedPolicies.has(row)).length;all.checked=rows.length>0&&selectedCount===rows.length;all.indeterminate=selectedCount>0&&selectedCount<rows.length})}
function renderFlat(){const rows=sortedConfigs(filteredPolicies()),totalPages=Math.max(1,Math.ceil(rows.length/flatPageSize));flatPage=Math.min(Math.max(1,flatPage),totalPages);const start=(flatPage-1)*flatPageSize,pageRows=rows.slice(start,start+flatPageSize);$('#flatBody').innerHTML=pageRows.length?pageRows.map(r=>{const index=configs.indexOf(r);return tableRow(r,index,'flat')+(index===viewConfigIndex?inlineCalendarRow(r,index,'flat'):'')}).join(''):'<tr><td colspan="12"><div class="empty">没有与当前筛选条件匹配的政策</div></td></tr>';$('#resultCount').textContent=`筛选结果，共 ${rows.length} 条配置`;$('#flatTotal').textContent=`共 ${rows.length} 条`;$('#pageSize').value=String(flatPageSize);$('#pageNumbers').innerHTML=compactPages(totalPages,flatPage).map(page=>typeof page==='number'?`<button class="page-btn ${flatPage===page?'active':''}" type="button" data-page="${page}">${page}</button>`:'<span class="page-gap">…</span>').join('');$('#prevPage').disabled=flatPage<=1||!rows.length;$('#nextPage').disabled=flatPage>=totalPages||!rows.length;$('#pageStatus').textContent=rows.length?`第 ${flatPage}/${totalPages} 页`:'第 0/0 页';updateBulkSelectionUi()}
function renderMonthTree(){const months=[...availableMonths].sort((a,b)=>b.localeCompare(a)),years=[...new Set(months.map(x=>x.slice(0,4)))].sort((a,b)=>b.localeCompare(a));$('#monthTree').innerHTML=years.map(year=>`<section class="timeline-year"><button class="timeline-year-label" type="button">${year}年</button><div class="timeline-months">${months.filter(x=>x.startsWith(`${year}-`)).map(key=>{const m=Number(key.slice(5)),count=configs.filter(r=>r.month===key).length;return `<button class="timeline-month ${key===selectedMonth?'active':''}" type="button" data-month="${key}"><span class="timeline-dot"></span><span>${m}月</span>${count?`<span class="month-count">${count}</span>`:'<span></span>'}</button>`}).join('')}</div></section>`).join('');const active=$('#monthTree .timeline-month.active');if(active)requestAnimationFrame(()=>{$('#monthTree').scrollTop=Math.max(0,active.offsetTop-150)})}
function renderMonthPolicies(){const rows=sortedConfigs(configs.filter(r=>r.month===selectedMonth));if(rows.length&&!rows.includes(configs[activeConfigIndex]))activeConfigIndex=configs.indexOf(rows[0]);if(!rows.length)activeConfigIndex=null;$('#detailSubtitle').textContent=`仅展示当前月份，共 ${rows.length} 条配置`;$('#monthPolicyBody').innerHTML=rows.length?rows.map(r=>{const index=configs.indexOf(r);return tableRow(r,index,'month')+(index===viewConfigIndex?inlineCalendarRow(r,index,'month'):'')}).join(''):'<tr><td colspan="12"><div class="empty">该月份暂无返利配置</div></td></tr>';const all=$('[data-select-all="month"]');if(all)all.checked=false;if(activeConfigIndex===null)$('#detailContent').innerHTML='<div class="empty-detail">选择其他月份或新增配置</div>';else renderDetail(activeConfigIndex)}
function setTreeMode(){treeMode=false;$('#treeModeView').classList.add('hidden');$('#flatListView').classList.remove('hidden');renderFlat()}
function calendarHtml(r,start=r.start,end=r.end){const months=[];let cursor=monthOf(start),last=monthOf(end);while(cursor<=last){months.push(cursor);const [y,m]=cursor.split('-').map(Number),n=new Date(y,m,1);cursor=`${n.getFullYear()}-${String(n.getMonth()+1).padStart(2,'0')}`;if(months.length>24)break}return months.map(month=>calendarMonthHtml({...r,month},start,end)).join('')}
function calendarMonthHtml(r,start,end){const [y,m]=r.month.split('-').map(Number),count=new Date(y,m,0).getDate(),names=['周日','周一','周二','周三','周四','周五','周六'],firstDow=new Date(y,m-1,1).getDay(),headers=Array.from({length:14},(_,i)=>names[(firstDow+i)%7]),periodCount=Math.ceil(count/7);const periods=Array.from({length:Math.ceil(count/14)},(_,i)=>{const periodStart=i*14+1,periodEnd=Math.min(periodStart+13,count),firstPeriod=i*2+1,lastPeriod=Math.min(firstPeriod+1,periodCount),periodLabel=firstPeriod===lastPeriod?`第${firstPeriod}周期`:`第${firstPeriod}—${lastPeriod}周期`,cards=Array.from({length:14},(_,offset)=>{const day=periodStart+offset;if(day>count)return '<div class="calendar-empty"></div>';const date=`${r.month}-${String(day).padStart(2,'0')}`,meta=getDateMeta(date),active=date>=start&&date<=end,base=effectiveValue(r,date,'base'),price=effectiveValue(r,date,'price'),isHoliday=meta.type==='法定节假日',isSunday=meta.dayGroup==='周日',typeTag=isHoliday?`<span class="day-type-tag holiday">${holidayNames.get(date)||'节假日'}</span>`:(isSunday?'<span class="day-type-tag sunday">周日</span>':'');return `<div class="day-card ${isHoliday?'is-holiday ':(isSunday?'is-sunday ':'')}${active?'':'inactive'}"><div class="day-card-head"><span class="day-number">${day}</span>${typeTag}</div><div class="day-metrics"><div class="day-metric"><span class="day-weight">${active?base:'—'} ${active?'<small>kg</small>':''}</span></div><div class="day-metric"><span class="day-price">${active?Number(price).toFixed(2):'—'} ${active?'<small>元/kg</small>':''}</span></div></div></div>`}).join('');return `<div class="calendar-period"><div class="calendar-period-label"><span>${periodLabel}</span><strong>${periodStart}—${periodEnd}日</strong></div><div class="calendar-grid">${cards}</div></div>`}).join('');return `<div class="calendar-month-head"><strong>${y}年${m}月</strong><div class="calendar-legend"><span class="calendar-legend-item sunday">周日</span><span class="calendar-legend-item holiday">法定节假日</span></div></div><div class="calendar-scroll"><div class="calendar-panel"><div class="calendar-weekdays">${headers.map(x=>`<div class="calendar-weekday">${x}</div>`).join('')}</div>${periods}</div></div>`}
function valueText(v,unit){return usable(v)?`${v} ${unit}`:'继承上一级'}
function renderDetail(index){activeConfigIndex=index;const r=configs[index];if(!r)return;const year=Number(r.month.slice(0,4)),holidayStatus=holidayLoadedYears.has(year)?`${year}年国家法定节假日已导入`:`${year}年国家法定节假日未导入`;$$('#monthPolicyBody .policy-row').forEach(x=>x.classList.toggle('active',Number(x.dataset.rowIndex)===index));$('#detailContent').innerHTML=`<div class="scope-path"><span>当前配置：<strong>${r.site} / ${r.endType}·${r.endpoint} / ${r.product} / ${r.cargo} / ${r.band}</strong></span><span><button class="btn text" data-detail-action="edit" data-index="${index}">编辑</button><button class="btn text" data-detail-action="delete" data-index="${index}" style="color:var(--danger)">删除</button></span></div><div class="calendar-title-row"><div class="section-title">当月每日配置</div><div class="holiday-status">${holidayStatus}</div></div>${calendarHtml(r)}`}
function renderImports(){$('#importBody').innerHTML=importRows.map(r=>`<tr><td><button class="link" data-view-import="${r[0]}">${r[0]}</button></td><td>${r[1]}</td><td><span class="tag ${r[2]==='导入成功'?'gold':(r[2]==='处理中'?'orange':'red')}">${r[2]}</span></td><td class="number">${r[3].toLocaleString()}</td><td class="number">${r[4].toLocaleString()}</td><td class="number">${r[5].toLocaleString()}</td><td class="number">${r[6].toLocaleString()}</td><td>${r[7]}</td><td>${r[8]}</td><td>${r[5]>0?`<button class="btn text" data-view-problems="${r[0]}">查看问题数据</button>`:'<button class="btn text" data-view-import="'+r[0]+'">查看</button>'}</td></tr>`).join('')}
function problemRowsForActiveBatch(){return problemRows.filter(row=>row.batch===activeProblemBatch)}
function problemInput(field,value,type='text'){return `<input class="problem-edit-control" type="${type}" data-problem-field="${field}" value="${String(value??'').replaceAll('&','&amp;').replaceAll('"','&quot;')}" />`}
function problemRowMarkup(row){const editing=problemEditingId===row.id,date=editing?`<div style="display:grid;gap:4px">${problemInput('start',row.start,'date')}${problemInput('end',row.end,'date')}</div>`:`<span class="date-inline">${row.start||'未填写'}<span class="muted"> 至 </span>${row.end||'未填写'}</span>`;return `<tr data-problem-id="${row.id}"><td><input class="checkbox problem-selector" type="checkbox" ${selectedProblemIds.has(row.id)?'checked':''} aria-label="选择Excel第${row.rowNo}行" /></td><td>${row.rowNo}</td><td>${date}</td><td>${editing?problemInput('site',row.site):row.site}</td><td>${editing?problemInput('endpoint',row.endpoint):row.endpoint}</td><td>${editing?problemInput('product',row.product):row.product}</td><td>${editing?problemInput('cargo',row.cargo):row.cargo}</td><td>${editing?problemInput('band',row.band):row.band}</td><td>${editing?problemInput('cycle',row.cycle):row.cycle}</td><td class="problem-reason"><span class="tag red">${row.reason}</span></td><td class="problem-status-sticky"><span class="tag ${row.status==='待修改'?'red':'orange'}">${row.status}</span></td><td class="problem-actions-sticky"><div class="problem-actions">${editing?`<button class="btn text" data-problem-action="save">保存</button><button class="btn text" data-problem-action="cancel">取消</button>`:`<button class="btn text" data-problem-action="edit">编辑</button>`}<button class="btn text" data-problem-action="delete" style="color:var(--danger)">删除</button></div></td></tr>`}
function renderProblemPool(){const rows=problemRowsForActiveBatch();$('#problemPoolSubtitle').textContent=`导入批次 ${activeProblemBatch}`;$('#problemPoolCount').textContent=`共 ${rows.length} 条问题数据`;$('#problemSelectedCount').textContent=`已选 ${selectedProblemIds.size} 条`;$('#downloadSelectedProblems').disabled=selectedProblemIds.size===0;const all=$('#selectAllProblems');all.checked=rows.length>0&&rows.every(row=>selectedProblemIds.has(row.id));all.indeterminate=selectedProblemIds.size>0&&!all.checked;$('#problemPoolBody').innerHTML=rows.length?rows.map(problemRowMarkup).join(''):'<tr><td colspan="12"><div class="problem-pool-empty">当前批次没有待处理问题数据</div></td></tr>'}
function openProblemPool(batch){activeProblemBatch=batch;problemEditingId='';selectedProblemIds.clear();renderProblemPool();$('#overlay').classList.add('show');$('#problemPoolDrawer').classList.add('show');$('#problemPoolDrawer').setAttribute('aria-hidden','false')}
function saveProblemRow(tableRow,problem){['start','end','site','endpoint','product','cargo','band','cycle'].forEach(field=>{const input=$(`[data-problem-field="${field}"]`,tableRow);if(input)problem[field]=input.value.trim()});problem.reason='待重新校验';problem.status='待校验';problemEditingId='';renderProblemPool();toast('问题数据已修改，请重新校验或下载后二次导入')}
function xmlEscape(value){return String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&apos;')}
function downloadProblemRows(rows){if(!rows.length){toast('请选择需要下载的问题数据');return}const columns=[['原Excel行号','rowNo'],['生效开始日期','start'],['生效结束日期','end'],['寄件网点','site'],['目的流向','endpoint'],['产品类型','product'],['货物类型','cargo'],['公斤段','band'],['考核周期','cycle'],['日基准量','dailyBase'],['日返利单价','dailyPrice'],['工作日基准量','workdayBase'],['工作日返利单价','workdayPrice'],['周日基准量','sundayBase'],['周日返利单价','sundayPrice'],['节假日基准量','holidayBase'],['节假日返利单价','holidayPrice'],['失败原因','reason']];const xml=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="问题数据"><Table><Row>${columns.map(([name])=>`<Cell><Data ss:Type="String">${xmlEscape(name)}</Data></Cell>`).join('')}</Row>${rows.map(row=>`<Row>${columns.map(([,key])=>`<Cell><Data ss:Type="String">${xmlEscape(row[key])}</Data></Cell>`).join('')}</Row>`).join('')}</Table></Worksheet></Workbook>`,blob=new Blob([xml],{type:'application/vnd.ms-excel;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`${activeProblemBatch}_问题数据_${rows.length}条.xls`;link.click();setTimeout(()=>URL.revokeObjectURL(url),0);toast(`已下载 ${rows.length} 条问题数据，可修正后二次导入`)}
function setEndpointOptions(value=''){const groups=[['分拨',['杭州分拨中心','宁波分拨中心','嘉兴分拨中心']],['营运区',[...new Set([...configs.filter(r=>r.endType==='营运区').map(r=>r.endpoint),'浙北营运区','浙东营运区'])]]];$('#eEndpoint').innerHTML=groups.map(([type,items])=>`<optgroup label="${type}">${items.map(x=>`<option data-type="${type}" ${x===value?'selected':''}>${x}</option>`).join('')}</optgroup>`).join('')}
function selectedEndpointType(){return $('#eEndpoint').selectedOptions[0]?.dataset.type||'分拨'}
function formRule(){return {dailyBase:$('#dailyBase').value,workdayBase:$('#workdayBase').value,sundayBase:$('#sundayBase').value,holidayBase:$('#holidayBase').value,dailyPrice:$('#dailyPrice').value,workdayPrice:$('#workdayPrice').value,sundayPrice:$('#sundayPrice').value,holidayPrice:$('#holidayPrice').value}}
function datesBetween(start,end){const out=[],d=new Date(`${start}T00:00:00`),last=new Date(`${end}T00:00:00`);while(d<=last&&out.length<740){out.push(formatDate(d));d.setDate(d.getDate()+1)}return out}
function renderEditorPreview(){const start=$('#eStart').value,end=$('#eEnd').value;if(!start||!end||start>end){$('#previewRange').textContent='请填写有效的生效日期范围';$('#dailyBody').innerHTML='';$('#dailyCalendarPreview').innerHTML='';return}const r={...formRule(),start,end},names=['周日','周一','周二','周三','周四','周五','周六'],dates=datesBetween(start,end);$('#previewRange').textContent=`${start} 至 ${end}，共 ${dates.length} 天；跨月将自动拆分`;$('#dailyBody').innerHTML=dates.map(date=>{const meta=getDateMeta(date);return `<tr><td>${date}</td><td>${names[meta.d.getDay()]}</td><td><span class="day-type-tag ${meta.type==='法定节假日'?'holiday':meta.type==='周日'?'sunday':''}">${meta.type==='法定节假日'?(holidayNames.get(date)||meta.type):meta.type}</span></td><td class="number"><strong>${effectiveValue(r,date,'base')}</strong></td><td class="number"><strong style="color:var(--brand-6)">${Number(effectiveValue(r,date,'price')).toFixed(2)}</strong></td></tr>`}).join('');$('#dailyCalendarPreview').innerHTML=calendarHtml(r,start,end)}
function setPreviewMode(mode){previewMode=mode;$('#previewListTab').classList.toggle('active',mode==='list');$('#previewCalendarTab').classList.toggle('active',mode==='calendar');$('#dailyListPreview').classList.toggle('hidden',mode!=='list');$('#dailyCalendarPreview').classList.toggle('hidden',mode!=='calendar')}
function nextMonth(value){const [y,m]=value.split('-').map(Number),d=new Date(y,m,1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function setFormValues(r){for(const id of ['dailyBase','workdayBase','sundayBase','holidayBase','dailyPrice','workdayPrice','sundayPrice','holidayPrice'])$(`#${id}`).value=r[id]??''}
function setEnabledSwitch(value){const enabled=Boolean(value);$('#eEnabled').classList.toggle('on',enabled);$('#eEnabled').setAttribute('aria-checked',String(enabled));$('#eEnabledText').textContent=enabled?'启用':'停用'}
function setDrawerReadonly(readonly){['eStart','eEnd','eCycle','eSite','eEndpoint','dailyBase','workdayBase','sundayBase','holidayBase','dailyPrice','workdayPrice','sundayPrice','holidayPrice','eEnabled'].forEach(id=>{$(`#${id}`).disabled=readonly});$$('.editor-multi-select').forEach(detail=>{detail.classList.toggle('disabled',readonly);if(readonly)detail.removeAttribute('open')});$('#saveConfig').classList.toggle('hidden',readonly);$('#editorDrawer .drawer-foot .close-layer').textContent=readonly?'关闭':'取消'}
function openDrawer(index=null){setDrawerReadonly(false);editIndex=index;$('#drawerTitle').textContent=index===null?'新增返利配置':'编辑返利配置';const r=index!==null?configs[index]:null;if(r){$('#eStart').value=r.start;$('#eEnd').value=r.end;$('#eCycle').value=r.cycle;$('#eSite').value=r.site;setEndpointOptions(r.endpoint);setEditorMultiValues('product',splitMulti(r.product));setEditorMultiValues('cargo',splitMulti(r.cargo));setEditorMultiValues('band',splitMulti(r.band));setEnabledSwitch(r.enabled!==false);setFormValues(r)}else{const month=selectedMonth||latestMonth();$('#eStart').value=`${month}-01`;$('#eEnd').value=`${month}-${String(daysInMonth(month)).padStart(2,'0')}`;$('#eCycle').value='周';setEndpointOptions();setEditorMultiValues('product',[]);setEditorMultiValues('cargo',[]);setEditorMultiValues('band',[]);setEnabledSwitch(true);setFormValues(defaults)}updateCycleHint();updateCombinationHint();renderEditorPreview();setPreviewMode('calendar');$('#overlay').classList.add('show');$('#editorDrawer').classList.add('show');$('#editorDrawer').setAttribute('aria-hidden','false')}
function closeLayers(){$('#editorDrawer').classList.remove('show');$('#problemPoolDrawer').classList.remove('show');$('#importModal').classList.remove('show');$('#holidayModal').classList.remove('show');$('#monthModal').classList.remove('show');$('#deleteMonthModal').classList.remove('show');$('#bulkDisableModal').classList.remove('show');$('#bulkDeleteModal').classList.remove('show');$('#overlay').classList.remove('show');$('#editorDrawer').setAttribute('aria-hidden','true');$('#problemPoolDrawer').setAttribute('aria-hidden','true');$('#importModal').setAttribute('aria-hidden','true');$('#holidayModal').setAttribute('aria-hidden','true');$('#monthModal').setAttribute('aria-hidden','true');$('#deleteMonthModal').setAttribute('aria-hidden','true');$('#bulkDisableModal').setAttribute('aria-hidden','true');$('#bulkDeleteModal').setAttribute('aria-hidden','true')}
function openMonthModal(){$('#newMonthInput').value=currentMonth;$('#overlay').classList.add('show');$('#monthModal').classList.add('show');$('#monthModal').setAttribute('aria-hidden','false')}
function openDeleteMonthModal(){if(!selectedMonth){toast('请先选择需要删除的月份');return}const count=configs.filter(r=>r.month===selectedMonth).length,[year,month]=selectedMonth.split('-');$('#deleteMonthTitle').textContent=`删除${year}年${Number(month)}月？`;$('#deleteMonthText').textContent=count?`该月份下有 ${count} 条返利配置，确认后将一并移除。`:'该月份暂无返利配置，确认后将从年月树中移除。';$('#overlay').classList.add('show');$('#deleteMonthModal').classList.add('show');$('#deleteMonthModal').setAttribute('aria-hidden','false')}
function openBulkDisableModal(){if(!selectedPolicies.size){toast('请先选择需要停用的政策');return}const enabledCount=[...selectedPolicies].filter(r=>r.enabled!==false).length,disabledCount=selectedPolicies.size-enabledCount;$('#bulkDisableText').textContent=`已选择 ${selectedPolicies.size} 条政策，其中 ${enabledCount} 条将被停用${disabledCount?`，${disabledCount} 条已停用将保持不变`:''}。`;$('#confirmBulkDisable').disabled=enabledCount===0;$('#overlay').classList.add('show');$('#bulkDisableModal').classList.add('show');$('#bulkDisableModal').setAttribute('aria-hidden','false')}
function canDeletePolicy(policy){return policy.start>formatDate(systemNow)}
function openBulkDeleteModal(){if(!selectedPolicies.size){toast('请先选择需要删除的政策');return}const deletable=[...selectedPolicies].filter(canDeletePolicy).length,retained=selectedPolicies.size-deletable;$('#bulkDeleteText').textContent=`已选择 ${selectedPolicies.size} 条政策，其中 ${deletable} 条尚未生效可删除${retained?`，${retained} 条已生效将保留`:''}。`;$('#confirmBulkDelete').disabled=deletable===0;$('#overlay').classList.add('show');$('#bulkDeleteModal').classList.add('show');$('#bulkDeleteModal').setAttribute('aria-hidden','false')}
function openImport(){pendingImportPlan=null;$('#fileInput').value='';$('#uploadStage').classList.remove('hidden');$('#previewStage').classList.add('hidden');$('#confirmImport').disabled=true;$('#step2').classList.remove('active');$('#step3').classList.remove('active');$('#overlay').classList.add('show');$('#importModal').classList.add('show');$('#importModal').setAttribute('aria-hidden','false')}
function nowText(){const d=new Date();return `${formatDate(d)} ${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}:${String(d.getSeconds()).padStart(2,'0')}`}
function importBatchNo(){return `IMP${formatDate(new Date()).replaceAll('-','')}${String(importSequence++).padStart(3,'0')}`}
function createImportPlan(name){const importedAt=nowText(),candidates=buildImportedPolicies(importedAt),matches=candidates.map(item=>configs.filter(old=>old.enabled!==false&&samePolicyDimension(old,item))),replacementCount=matches.filter(rows=>rows.length>0).length,previousCount=importRows.filter(row=>row[1]===name).length;return {name,importedAt,candidates,matches,replacementCount,newCount:candidates.length-replacementCount,totalRows:3,passedRows:2,failedRows:1,generatedCount:candidates.length,previousCount}}
function renderImportPlan(plan){$('#selectedFile').textContent=plan.name;$('#importTotalRows').textContent=plan.totalRows;$('#importPassedRows').textContent=plan.passedRows;$('#importFailedRows').textContent=plan.failedRows;$('#importGeneratedCount').textContent=plan.generatedCount;$('#importReplacementCount').textContent=plan.replacementCount;$('#importValidationText').textContent=plan.previousCount?`检测到同名文件已有 ${plan.previousCount} 个历史导入批次，已按当前启用政策重新校验`:'已完成格式、枚举、文件内重复和现有政策冲突校验';const history=plan.previousCount?`<strong>重复导入识别：</strong>同名文件此前已导入 ${plan.previousCount} 次；本次结果根据当前启用政策重新计算，不沿用上一次说明。<br />`:'';$('#importPreviewNotice').innerHTML=`${history}<strong>本次处理：</strong>${plan.newCount} 条新增，${plan.replacementCount} 条替换，${plan.failedRows} 条文件内重复数据进入信息池。确认后，命中的旧政策自动停用，本批次新政策启用，不会同时存在两条相同维度且日期重叠的启用政策。<br /><strong>排列组合：</strong>2 条通过校验的 Excel 数据各拆分为 2 × 3 × 4，共生成 ${plan.generatedCount} 条政策。`}
function showImportPreview(name){pendingImportPlan=createImportPlan(name);renderImportPlan(pendingImportPlan);$('#uploadStage').classList.add('hidden');$('#previewStage').classList.remove('hidden');$('#step2').classList.add('active');$('#confirmImport').disabled=false}
function openHolidayImport(){const year=selectedMonth.slice(0,4);$('#holidayYear').value=year;$('#holidayFileName').textContent=`${year}年国家法定节假日.xlsx`;$('#overlay').classList.add('show');$('#holidayModal').classList.add('show');$('#holidayModal').setAttribute('aria-hidden','false')}
function downloadTemplate(){const a=document.createElement('a');a.href='政策管理导入模板_四档公斤段.xlsx';a.download='政策管理导入模板_四档公斤段.xlsx';a.click();toast('导入模板已下载')}
function updateCycleHint(){$('#cycleHint').textContent=$('#eCycle').value==='周'?'按1—7日、8—14日、15—21日、22—28日、29日—月末分段汇总':'按自然月汇总每日实际货量与每日基准量'}
function deleteConfig(index){const r=configs[index];if(!r)return;if(!canDeletePolicy(r)){toast('该政策已经生效，不能删除，请使用停用');return}if(!window.confirm(`确认删除“${r.site}－${r.endpoint}－${r.product}”配置吗？`))return;selectedPolicies.delete(r);configs.splice(index,1);activeConfigIndex=null;setTreeMode(treeMode);updateBulkSelectionUi();toast('配置已删除')}
function renderPolicyScope(scope){if(scope==='month')renderMonthPolicies();else renderFlat()}
function handleInlineCalendarAction(e,scope){const btn=e.target.closest('[data-inline-calendar-action]');if(!btn)return false;viewConfigIndex=null;renderPolicyScope(scope);return true}
function handleRowAction(e,scope){const btn=e.target.closest('[data-row-action]');if(!btn)return;const index=Number(btn.dataset.index),action=btn.dataset.rowAction;if(action==='delete')deleteConfig(index);else if(action==='view'){viewConfigIndex=index;renderPolicyScope(scope)}else openDrawer(index)}
function splitByMonth(base){const result=[],first=monthOf(base.start),last=monthOf(base.end);let cursor=first;while(cursor<=last){const monthStart=`${cursor}-01`,monthEnd=`${cursor}-${String(daysInMonth(cursor)).padStart(2,'0')}`;result.push({...base,month:cursor,start:base.start>monthStart?base.start:monthStart,end:base.end<monthEnd?base.end:monthEnd});cursor=nextMonth(cursor);if(result.length>24)break}return result}
function findEnabledConflict(candidate,excludeIndex){return configs.findIndex((r,index)=>index!==excludeIndex&&r.enabled!==false&&r.site===candidate.site&&r.endpoint===candidate.endpoint&&r.product===candidate.product&&r.cargo===candidate.cargo&&r.band===candidate.band&&r.start<=candidate.end&&r.end>=candidate.start)}
function buildImportedPolicies(importedAt=nowText()){const common={...defaults,endType:'营运区',product:'融速达,精准零担',cargo:'轻泡,重泡,重货',band:'0kg-100kg,100kg-300kg,300kg-800kg,800kg-1500kg',cycle:'月',enabled:true,importedAt,importedBy:'李未'};return [
  ...expandCombinations({...common,month:'2026-10',siteCode:'8590006',site:'安龙站',endpointCode:'889990',endpoint:'浙北营运区',start:'2026-10-01',end:'2026-10-31'}),
  ...expandCombinations({...common,month:'2026-06',siteCode:'8590006',site:'安龙站',endpointCode:'771990',endpoint:'虚拟广西省区',start:'2026-06-01',end:'2026-06-30'})
]}
function samePolicyDimension(a,b){return a.site===b.site&&a.endpoint===b.endpoint&&a.product===b.product&&a.cargo===b.cargo&&a.band===b.band&&a.start<=b.end&&a.end>=b.start}
function showPolicyHomeAfterImport(){selectedPolicies.clear();$$('.tab').forEach(tab=>tab.classList.toggle('active',tab.dataset.tab==='configs'));$('#configsPanel').classList.remove('hidden');$('#importsPanel').classList.add('hidden');$('#filterStart').value='';$('#filterEnd').value='';$('#filterEnabled').value='';rangeDraftStart='';rangeDraftEnd='';Object.entries(policyFilterMeta).forEach(([key,placeholder])=>{const detail=$(`.multi-select[data-filter="${key}"]`);$$('input[type="checkbox"]',detail).forEach(item=>item.checked=false);updateFilterSummary(detail,key,placeholder);detail.removeAttribute('open')});updateFilterDateText();flatPage=1;setTreeMode(false)}
function saveConfig(){const start=$('#eStart').value,end=$('#eEnd').value,products=editorMultiValues('product'),cargos=editorMultiValues('cargo'),bands=editorMultiValues('band');if(!start||!end||start>end){toast('请填写有效的生效日期范围');return}if(!products.length||!cargos.length||!bands.length){toast('产品类型、货物类型和公斤段均至少选择一项');return}const prices=['dailyPrice','workdayPrice','sundayPrice','holidayPrice'].map(id=>$('#'+id).value),invalidPrice=prices.some(value=>value!==''&&String(value).split('.')[1]?.length>2);if(invalidPrice){toast('返利单价最多保留两位小数');return}if(!usable($('#dailyBase').value)||!usable($('#dailyPrice').value)){toast('日基准量和日返利单价必须填写');return}const previous=editIndex===null?null:configs[editIndex],enabled=$('#eEnabled').classList.contains('on'),base={site:$('#eSite').value,endType:selectedEndpointType(),endpoint:$('#eEndpoint').value,product:products.join(','),cargo:cargos.join(','),band:bands.join(','),start,end,cycle:$('#eCycle').value,enabled,importedAt:previous?.importedAt||'—',importedBy:previous?.importedBy||'—',...formRule()};const items=splitByMonth(base).flatMap(expandCombinations),keys=new Set(items.map(item=>[item.month,item.site,item.endpoint,item.product,item.cargo,item.band,item.start,item.end].join('|')));if(keys.size!==items.length){toast('拆分结果存在重复组合，请调整适用范围');return}if(enabled){const conflictItem=items.find(item=>findEnabledConflict(item,editIndex)>=0);if(conflictItem){toast(`无法保存：${conflictItem.product}／${conflictItem.cargo}／${conflictItem.band} 与现有启用政策日期重叠`);return}}items.forEach(item=>availableMonths.add(item.month));if(editIndex===null)configs.unshift(...items);else configs.splice(editIndex,1,...items);selectedMonth=items[0].month;activeConfigIndex=configs.indexOf(items[0]);closeLayers();setTreeMode(treeMode);toast(items.length>1?`校验通过，已拆分并保存 ${items.length} 条原子政策`:(editIndex===null?'配置已新增':'配置已保存'))}
loadOfficialHolidays2026();selectedMonth=currentMonth;renderImports();setEndpointOptions();updateCycleHint();renderEditorMultiSelects();renderPolicyFilters();setTreeMode();
$$('.tab').forEach(tab=>tab.addEventListener('click',()=>{$$('.tab').forEach(x=>x.classList.remove('active'));tab.classList.add('active');const imp=tab.dataset.tab==='imports';$('#configsPanel').classList.toggle('hidden',imp);$('#importsPanel').classList.toggle('hidden',!imp)}));
$('#importBody').addEventListener('click',event=>{const problems=event.target.closest('[data-view-problems]');if(problems){openProblemPool(problems.dataset.viewProblems);return}const batch=event.target.closest('[data-view-import]');if(batch)toast(`导入批次 ${batch.dataset.viewImport} 暂无需要处理的问题数据`)});
$('#problemPoolBody').addEventListener('change',event=>{const checkbox=event.target.closest('.problem-selector');if(!checkbox)return;const id=checkbox.closest('[data-problem-id]').dataset.problemId;if(checkbox.checked)selectedProblemIds.add(id);else selectedProblemIds.delete(id);renderProblemPool()});
$('#problemPoolBody').addEventListener('click',event=>{const button=event.target.closest('[data-problem-action]');if(!button)return;const tableRow=button.closest('[data-problem-id]'),id=tableRow.dataset.problemId,problem=problemRows.find(item=>item.id===id);if(!problem)return;const action=button.dataset.problemAction;if(action==='edit'){problemEditingId=id;renderProblemPool()}else if(action==='cancel'){problemEditingId='';renderProblemPool()}else if(action==='save')saveProblemRow(tableRow,problem);else if(action==='delete'){if(!window.confirm(`确认删除Excel第${problem.rowNo}行问题数据吗？`))return;const index=problemRows.indexOf(problem);if(index>=0)problemRows.splice(index,1);selectedProblemIds.delete(id);problemEditingId='';renderProblemPool();toast('问题数据已删除')}});
$('#selectAllProblems').addEventListener('change',event=>{problemRowsForActiveBatch().forEach(row=>{if(event.target.checked)selectedProblemIds.add(row.id);else selectedProblemIds.delete(row.id)});renderProblemPool()});
$('#downloadSelectedProblems').addEventListener('click',()=>downloadProblemRows(problemRowsForActiveBatch().filter(row=>selectedProblemIds.has(row.id))));$('#downloadAllProblems').addEventListener('click',()=>downloadProblemRows(problemRowsForActiveBatch()));
$('#problemReimport').addEventListener('click',()=>{closeLayers();openImport();setTimeout(()=>$('#fileInput').click(),0)});
$('#addMonthBtn').addEventListener('click',openMonthModal);$('#confirmAddMonth').addEventListener('click',()=>{const month=$('#newMonthInput').value;if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(month)){toast('请选择有效的年份和月份');return}const existed=availableMonths.has(month);availableMonths.add(month);selectedMonth=month;activeConfigIndex=null;closeLayers();setTreeMode(true);toast(existed?'该月份已存在，已为你定位':`已新增${Number(month.slice(0,4))}年${Number(month.slice(5))}月`)});
$('#deleteMonthBtn').addEventListener('click',openDeleteMonthModal);$('#confirmDeleteMonth').addEventListener('click',()=>{const deletedMonth=selectedMonth;for(let i=configs.length-1;i>=0;i--)if(configs[i].month===deletedMonth)configs.splice(i,1);availableMonths.delete(deletedMonth);if(!availableMonths.size)availableMonths.add(currentMonth);selectedMonth=[...availableMonths].sort((a,b)=>b.localeCompare(a))[0];activeConfigIndex=null;closeLayers();setTreeMode(true);const [year,month]=deletedMonth.split('-');toast(`已删除${year}年${Number(month)}月`)});
$('#collapseMonthPanel').addEventListener('click',()=>{monthPanelCollapsed=!monthPanelCollapsed;$('.detail-layout').classList.toggle('month-panel-collapsed',monthPanelCollapsed);const button=$('#collapseMonthPanel'),label=monthPanelCollapsed?'向右展开生效年月':'向左收起生效年月';button.textContent=monthPanelCollapsed?'›':'‹';button.setAttribute('aria-label',label);button.title=label});
$('#calendarToggle').addEventListener('click',()=>{calendarCollapsed=!calendarCollapsed;const content=$('.detail-content'),button=$('#calendarToggle');content.classList.toggle('calendar-collapsed',calendarCollapsed);button.setAttribute('aria-expanded',String(!calendarCollapsed));$('#calendarToggleText').textContent=calendarCollapsed?'展开日历':'收起日历';button.title=calendarCollapsed?'展开当月每日配置日历':'收起当月每日配置日历'});
$('#monthTree').addEventListener('click',e=>{const month=e.target.closest('[data-month]');if(month){selectedMonth=month.dataset.month;activeConfigIndex=null;renderMonthTree();renderMonthPolicies();return}const year=e.target.closest('.timeline-year-label');if(year)year.parentElement.classList.toggle('collapsed')});
function handleRowSelection(event){const box=event.target.closest('.row-selector');if(!box)return;const row=configs[Number(box.dataset.selectRow)];if(!row)return;if(box.checked)selectedPolicies.add(row);else selectedPolicies.delete(row);updateBulkSelectionUi()}
$('#monthPolicyBody').addEventListener('change',handleRowSelection);$('#flatBody').addEventListener('change',handleRowSelection);
$('#monthPolicyBody').addEventListener('click',e=>{if(e.target.matches('.row-selector'))return;if(handleInlineCalendarAction(e,'month'))return;const btn=e.target.closest('[data-row-action]');if(btn){handleRowAction(e,'month');return}const row=e.target.closest('[data-row-index]');if(row)renderDetail(Number(row.dataset.rowIndex))});
$('#flatBody').addEventListener('click',e=>{if(e.target.matches('.row-selector'))return;if(handleInlineCalendarAction(e,'flat'))return;const btn=e.target.closest('[data-row-action]');if(btn){handleRowAction(e,'flat');return}const row=e.target.closest('[data-row-index]');if(row){const index=Number(row.dataset.rowIndex);selectedMonth=configs[index].month;activeConfigIndex=index;setTreeMode(true)}});$('#detailContent').addEventListener('click',e=>{const btn=e.target.closest('[data-detail-action]');if(!btn)return;const index=Number(btn.dataset.index);if(btn.dataset.detailAction==='delete')deleteConfig(index);else openDrawer(index)});
$$('[data-select-all]').forEach(box=>box.addEventListener('change',()=>{const rows=selectionScopeRows(box.dataset.selectAll);rows.forEach(row=>{if(box.checked)selectedPolicies.add(row);else selectedPolicies.delete(row)});const body=box.dataset.selectAll==='flat'?'#flatBody':'#monthPolicyBody';$$(`${body} .row-selector`).forEach(item=>{item.checked=box.checked});updateBulkSelectionUi()}));
$('#refreshBtn').addEventListener('click',()=>{renderFlat();toast('列表已刷新')});
$('#filterDateRange').addEventListener('click',e=>{e.stopPropagation();const popover=$('#filterDatePopover'),opening=popover.classList.contains('hidden');$$('.multi-select[open]').forEach(item=>item.removeAttribute('open'));if(opening){rangeDraftStart=$('#filterStart').value;rangeDraftEnd=$('#filterEnd').value;rangeCalendarMonth=(rangeDraftStart||currentMonth).slice(0,7);renderRangeCalendar()}popover.classList.toggle('hidden',!opening);$('#filterDateRange').setAttribute('aria-expanded',String(opening))});
$('#filterDatePopover').addEventListener('click',e=>e.stopPropagation());
$('#rangePrevMonth').addEventListener('click',()=>moveRangeMonth(-1));
$('#rangeNextMonth').addEventListener('click',()=>moveRangeMonth(1));
$('#rangeCalendarDays').addEventListener('click',e=>{const day=e.target.closest('[data-range-date]');if(!day)return;const date=day.dataset.rangeDate;if(!rangeDraftStart||rangeDraftEnd){rangeDraftStart=date;rangeDraftEnd=''}else if(date<rangeDraftStart){rangeDraftStart=date;rangeDraftEnd=''}else rangeDraftEnd=date;renderRangeCalendar()});
$('#filterDateConfirm').addEventListener('click',()=>{if(!rangeDraftStart||!rangeDraftEnd){toast('请依次选择开始日期和结束日期');return}$('#filterStart').value=rangeDraftStart;$('#filterEnd').value=rangeDraftEnd;updateFilterDateText();closeFilterDatePicker()});
$('#filterDateClear').addEventListener('click',()=>{rangeDraftStart='';rangeDraftEnd='';$('#filterStart').value='';$('#filterEnd').value='';updateFilterDateText();closeFilterDatePicker()});
document.addEventListener('click',e=>{if(!e.target.closest('.date-range-picker'))closeFilterDatePicker();$$('.multi-select[open]').forEach(detail=>{if(!detail.contains(e.target))detail.removeAttribute('open')})});
$('#policyQuery').addEventListener('click',()=>{const start=$('#filterStart').value,end=$('#filterEnd').value;if(start&&end&&start>end){toast('生效日期开始时间不能晚于结束时间');return}selectedPolicies.clear();flatPage=1;updateFilterDateText();closeFilterDatePicker();renderFlat();$$('.multi-select[open]').forEach(item=>item.removeAttribute('open'))});
$('#policyReset').addEventListener('click',()=>{selectedPolicies.clear();$('#filterStart').value='';$('#filterEnd').value='';$('#filterEnabled').value='';rangeDraftStart='';rangeDraftEnd='';flatPage=1;updateFilterDateText();closeFilterDatePicker();Object.entries(policyFilterMeta).forEach(([key,placeholder])=>{const detail=$(`.multi-select[data-filter="${key}"]`);$$('input[type="checkbox"]',detail).forEach(item=>item.checked=false);const search=$('.multi-search',detail);if(search){search.value='';search.dispatchEvent(new Event('input'))}updateFilterSummary(detail,key,placeholder);detail.removeAttribute('open')});renderFlat()});
$('#pageSize').addEventListener('change',e=>{flatPageSize=Number(e.target.value)||20;flatPage=1;renderFlat()});
$('#prevPage').addEventListener('click',()=>{if(flatPage>1){flatPage-=1;renderFlat()}});
$('#nextPage').addEventListener('click',()=>{const totalPages=Math.max(1,Math.ceil(filteredPolicies().length/flatPageSize));if(flatPage<totalPages){flatPage+=1;renderFlat()}});
$('#pageNumbers').addEventListener('click',e=>{const button=e.target.closest('[data-page]');if(!button)return;flatPage=Number(button.dataset.page);renderFlat()});
$('#addBtn').addEventListener('click',()=>openDrawer());$('#detailAdd').addEventListener('click',()=>openDrawer());
$('#bulkDisableBtn').addEventListener('click',openBulkDisableModal);$('#confirmBulkDisable').addEventListener('click',()=>{const enabledRows=[...selectedPolicies].filter(r=>r.enabled!==false);enabledRows.forEach(r=>{r.enabled=false});const count=enabledRows.length;selectedPolicies.clear();closeLayers();renderFlat();toast(`已停用 ${count} 条政策`)});
$('#bulkDeleteBtn').addEventListener('click',openBulkDeleteModal);$('#confirmBulkDelete').addEventListener('click',()=>{const deletable=new Set([...selectedPolicies].filter(canDeletePolicy)),retained=selectedPolicies.size-deletable.size;for(let i=configs.length-1;i>=0;i--)if(deletable.has(configs[i]))configs.splice(i,1);selectedPolicies.clear();closeLayers();renderFlat();toast(`已删除 ${deletable.size} 条未生效政策${retained?`，${retained} 条已生效政策已保留`:''}`)});
$('#importBtn').addEventListener('click',openImport);$('#detailImport').addEventListener('click',openImport);$('#importBtn2').addEventListener('click',openImport);$('#holidayImportBtn').addEventListener('click',openHolidayImport);
$('#chooseHolidayFile').addEventListener('click',()=>$('#holidayFile').click());$('#holidayFile').addEventListener('change',e=>{if(e.target.files[0])$('#holidayFileName').textContent=e.target.files[0].name});$('#loadOfficialHoliday').addEventListener('click',()=>{$('#holidayYear').value='2026';$('#holidayFileName').textContent='2026年国家法定节假日_国务院办公厅.xlsx';toast('已加载2026年官方节假日示例')});$('#confirmHolidayImport').addEventListener('click',()=>{const year=Number($('#holidayYear').value);if(year===2026)loadOfficialHolidays2026();else holidayLoadedYears.add(year);closeLayers();if(activeConfigIndex!==null)renderDetail(activeConfigIndex);toast(`${year}年国家法定节假日导入成功`)});
$('#eCycle').addEventListener('change',updateCycleHint);$('#eStart').addEventListener('change',()=>{updateCombinationHint();renderEditorPreview()});$('#eEnd').addEventListener('change',()=>{updateCombinationHint();renderEditorPreview()});$$('.config-input').forEach(input=>input.addEventListener('input',renderEditorPreview));
$('#eEnabled').addEventListener('click',()=>setEnabledSwitch(!$('#eEnabled').classList.contains('on')));
$('#previewListTab').addEventListener('click',()=>setPreviewMode('list'));$('#previewCalendarTab').addEventListener('click',()=>setPreviewMode('calendar'));$('#saveConfig').addEventListener('click',saveConfig);
$('#chooseFile').addEventListener('click',()=>{$('#fileInput').value='';$('#fileInput').click()});$('#replaceFile').addEventListener('click',()=>{$('#fileInput').value='';$('#fileInput').click()});$('#fileInput').addEventListener('change',e=>{if(e.target.files[0])showImportPreview(e.target.files[0].name)});
$('#confirmImport').addEventListener('click',()=>{if(!pendingImportPlan){toast('请先选择并校验导入文件');return}$('#step3').classList.add('active');const plan=createImportPlan(pendingImportPlan.name),batch=importBatchNo();let replaced=0;plan.candidates.forEach(item=>{configs.forEach(old=>{if(old.enabled!==false&&samePolicyDimension(old,item)){old.enabled=false;replaced+=1}});availableMonths.add(item.month)});configs.unshift(...plan.candidates);importRows.unshift([batch,plan.name,plan.failedRows?'部分失败':'导入成功',plan.totalRows,plan.passedRows,plan.failedRows,replaced,'李未',plan.importedAt]);if(plan.failedRows){const template=problemRows[0];problemRows.push({...template,id:`ERR${String(problemRows.length+1).padStart(5,'0')}`,batch,rowNo:4,reason:'文件内重复配置：后出现的数据未导入',status:'待修改'})}renderImports();selectedMonth='2026-10';activeConfigIndex=0;pendingImportPlan=null;setTimeout(()=>{closeLayers();showPolicyHomeAfterImport();toast(`导入完成：新增 ${plan.newCount} 条，替换 ${replaced} 条，${plan.failedRows} 条进入信息池`);if(plan.failedRows)openProblemPool(batch)},350)});
$('#downloadTemplate').addEventListener('click',downloadTemplate);$$('.download-template').forEach(x=>x.addEventListener('click',downloadTemplate));$$('.close-layer').forEach(x=>x.addEventListener('click',closeLayers));$('#overlay').addEventListener('click',closeLayers);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeLayers()});
